DROP DATABASE IF EXISTS appbnb;

CREATE DATABASE appbnb;

USE appbnb;

CREATE TABLE photos (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(255) NOT NULL ,
  description VARCHAR(255) DEFAULT ''
);

CREATE TABLE header (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  avg FLOAT NOT NULL,
  reviews INT NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  superUser BOOLEAN NOT NULL DEFAULT 0
);
